# Initialize pages package
from .Dashboard import show_dashboard
from .add_Stocks import show_add_stocks
from .Portfolio_value import show_overview
from .Risk_metrics import show_risk_metrics
from .Performance_Analysis import show_performance_analysis
from .Portfolio_Optimization import show_optimization
from .Market_News import show_market_news
from .Rebalance import show_rebalancing
from .Upload_Portfolio import show_settings
